### ISSUE TITLE
打包后启动npm run docs-dev，报错Cannot set property 'lastHMRTimestamp' of undefined

### ISSUE THREAD

**Issue by yc910920** [dewfall123/vitepress-for-component#12]
项目无法启动，另外可否增加一份说明，怎样在已有项目引入VFC？

**Comment by dewfall123** [comment]
能贴一下报错堆栈吗？最好能提供可复现的仓库

和vitepress一样使用就行，例如新建一个docs目录，添加index.md和.vitepress配置...等等

**Comment by yc910920** [comment]
多谢，我自己解决了是node版本的问题，升级到稳定版本就没这个问题了
