### ISSUE TITLE
vue 自定义指令，如何在vitepress 友好使用？

### ISSUE THREAD

**Issue by bhabgs** [dewfall123/vitepress-for-component#14]
vitepress 里使用 vue的自定义指令后，会提示相关错误。
![image](https://user-images.githubusercontent.com/19221378/112080844-a055f600-8bbd-11eb-85b8-c310867fa5a7.png)

`custom directive is missing corresponding SSR transform and will be ignored.`

**Comment by dewfall123** [comment]
参考这个  https://github.com/vuejs/vue-next/issues/3298#issuecomment-785687683

传入ssr 自定义指令配置试下
```js
// docs\.vitepress\config.js

vueOptions: {
    template: {
      ssr: true,
      compilerOptions: {
        directiveTransforms: {
          test: () => {
            return {
              props: [],
              needRuntime: true,
            };
          },
        },
      },
    },
  },
```

**Comment by bhabgs** [comment]
感谢您的分享，不知道您的解决方案是否能生效，我通过查看issuse 找到了 vitepress 相关布丁。
https://github.com/antfu/vite-ssg/issues/29
