### ISSUE TITLE
build 后页面布局异常

### ISSUE THREAD

**Issue by FuZhouJohn** [dewfall123/vitepress-for-component#15]
**Describe the bug**

执行 docs-build-serve 命令后打开网页样式错误，dev 时一切正常

**To Reproduce**

1. run `yarn docs-build-serve`
2. open URL

**Expected behavior**

网页样式正常

**System Info**
- vitepress-for-component version:0.14.2/0.13.1
- vite version:v2.1.5
- Node version:v12.18.3
- OS version:Windows 10.0 20H2; x64

**Additional context**
![image](https://user-images.githubusercontent.com/25957460/114584953-b97e2e00-9cb5-11eb-8395-f56b7d54e802.png)

相关 github 地址：https://github.com/fuzhoujohn/bass-ui

**Comment by FuZhouJohn** [comment]
页面无报错 
![image](https://user-images.githubusercontent.com/25957460/114585343-1f6ab580-9cb6-11eb-97b6-fc697ce8e9a0.png)
![image](https://user-images.githubusercontent.com/25957460/114585409-2ee9fe80-9cb6-11eb-8a40-43aa85bcbb3e.png)

**Comment by dewfall123** [comment]
已修复 更新下版本。
