### ISSUE TITLE
能够支持代码可编辑吗？

### ISSUE THREAD

**Issue by colgin** [dewfall123/vitepress-for-component#16]
现在代码能在页面上跑起来，但是要想编辑代码的话，需要跳转到codepen，如果能够在当前页面可以编辑代码，同时能看到效果，那就更好了。

**Comment by dewfall123** [comment]
以现在的处理逻辑不太好实现。
而且编辑代码比较复杂，这个工具主要针对文档展示，暂时没计划去实现。

**Comment by colgin** [comment]
Ok, 感谢
