### ISSUE TITLE
引入docs目录外的组件会报错

### ISSUE THREAD

**Issue by yiqia** [dewfall123/vitepress-for-component#29]
docs目录下新建了一个文件夹叫demo,里面有一个demo.vue文件，通过./index.zh-CN.md引入demo，demo中引入了docs文件夹外的组件通过../../components/xxx/xxx.tsx，但运行起来报错，查看了.temp文件夹里的文件，目录结构不一致导致的，无法引入docs文件夹外的组件，需要重复复制代码到docs文件夹里

**Comment by dewfall123** [comment]
1. 可以对路径加一层`../` (不推荐).
```
原因是，所有文件往.temp里面移了一层.
```
 2. or 使用import { xx } from 'packageName/you/file'这种方式，用`cli`生成的项目是会配置一个alias的，（这样的路径对demo来说也更符合实际使用一些）.
```
  alias: {
    // 为了能在demo中正确的使用  import { X } from 'packageName'
    [`packageName`]: resolve('./src'),
  },
```
3. or 把`.vue`文件和`.md`文件放docs外的目录下面，按[这种组织形式](https://dewfall123.github.io/vitepress-for-component/#_2-%E5%83%8F-dumi-%E4%B8%80%E6%A0%B7%E7%9A%84%E7%BB%84%E7%BB%87%E6%96%87%E4%BB%B6).
