### ISSUE TITLE
无法查看 CodePen 代码示例 

### ISSUE THREAD

**Issue by Turkyden** [dewfall123/vitepress-for-component#31]
点击查看代码示例后，发现合成的代码有问题，无法预览 :-(

另外，如何开启 CodesandBox 预览呢？ @dewfall123 

![image](https://user-images.githubusercontent.com/24560160/130187876-0daa1527-55be-496a-bfb8-92ff0c8b5027.png)

```js
new Vue({
	el: '#app', 
	import { useSize } from 'ahooks-vue';
import { ref } from 'vue';

  setup() {
    const divRef = ref(null);
    const size = useSize(divRef, {
      onChange: () => {
        console.log('size change');
      },
    });

    return {
      divRef,
      size,
    };
  },
};
})
```

**Comment by Turkyden** [comment]
项目很不错，但是出了点 Bug，希望有空可以修一下哈！感谢~

https://vue-typical.vercel.app/basic/

**Comment by dewfall123** [comment]
感觉codepen处理太麻烦，（或许我没找到合适的文档）
在`v0.16.0` 之后改为了采用 https://sfc.vuejs.org/ 
[demo文档说明](https://dewfall123.github.io/vitepress-for-component/guide/write-demo.html#demo%E5%9C%A8%E7%BA%BF%E6%BC%94%E7%A4%BA)

**Comment by Turkyden** [comment]
好的，感谢哦！
