### ISSUE TITLE
yarn build 完成后有语法报错！

### ISSUE THREAD

**Issue by dengshicheng1996** [dewfall123/vitepress-for-component#40]
![image](https://user-images.githubusercontent.com/41374066/140859566-923c6ea5-43b6-425e-be97-8903b126ab7f.png)

**Comment by dewfall123** [comment]
新的template修复了这个问题，可以重新运行`yarn create vlib`，https://github.com/dewfall123/vlib-template/commit/225e06a979a6b1d0ef29331cb8dbada4be2aefe0

也可以直接更新下vue-tsc版本，修改下type命令为 `vue-tsc --declaration --emitDeclarationOnly`
 https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc

或者采用其它dts生成方案都行
