### ISSUE TITLE
yarn create vlib 创建失败

### ISSUE THREAD

**Issue by liu-collab** [dewfall123/vitepress-for-component#41]
![image](https://user-images.githubusercontent.com/63389142/141024968-5ef610d1-2bdf-418f-abfc-4d63636b9fc0.png)
这个不能这么用吗还是哪里有问题

**Comment by dewfall123** [comment]
估计是yarn安装的问题  参考https://juejin.cn/post/6844904111570190349 排查下

**Comment by liu-collab** [comment]
解决了
