### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by MaybeQHL** [dewfall123/vitepress-for-component#42]
关键代码:  const decodedHtmlStr = computed(() => decodeURIComponent(props.htmlStr ?? ""));
报错信息: Uncaught SyntaxError: Unexpected token ?

**Comment by dewfall123** [comment]
你是怎么使用的呢？ 提供下复现步骤

[使用文档](https://dewfall123.github.io/vitepress-for-component/guide/getting-started.html)

**Comment by MaybeQHL** [comment]
[谷歌浏览器正常，QQ浏览器报错

![image](https://user-images.githubusercontent.com/34638673/141888136-7c13d39e-7c48-439c-af24-1bc4cc08dc9c.png)
拉下来代码直接运行

**Comment by MaybeQHL** [comment]
如果我要自己编写一个测试用的组件
![image](https://user-images.githubusercontent.com/34638673/141889707-c5a41bad-b268-44d9-8bc2-1d05e46c2e79.png)
如何全局注册

**Comment by dewfall123** [comment]
> 如何全局注册

自定义主题，在theme文件里能注册

https://github.com/dewfall123/vitepress-for-component/blob/master/docs/.vitepress/theme/index.js

**Comment by MaybeQHL** [comment]
好的谢谢

**Comment by MaybeQHL** [comment]
另外再问下代码片段可否定义主题颜色。

**Comment by dewfall123** [comment]
可以这样引入css  https://vitepress.vuejs.org/guide/theming.html#customizing-css

然后覆盖这里的样式 https://github.com/dewfall123/vitepress-for-component/blob/master/src/client/theme-default/styles/code.css
