### ISSUE TITLE
使用yarn create vlib脚本创建的项目，如果使用pnpm i安装依赖，yarn dev后访问页面报错

### ISSUE THREAD

**Issue by zhangshichun** [dewfall123/vitepress-for-component#43]
**Describe the bug**
```
pnpm i
yarn dev
访问：http://localhost:3001/
```
[vite] Internal server error: (0 , import_vite.transformWithEsbuild) is not a function
  Plugin: vite:vue

**Comment by zhangshichun** [comment]
猜测和锁 "vite": "2.4.1"版本有关？

**Comment by dewfall123** [comment]
升级了vite版本，应该可以了
