### ISSUE TITLE
打包前后Css样式不一致问题

### ISSUE THREAD

**Issue by peterroe** [dewfall123/vitepress-for-component#47]
能不能把默认css样式也一同打包，我发现组件发布的样式和这个项目预览的不一样，例如，用这个文档会默认为table表格加一些样式，但是打包之后，样式没有了，看起来很不一致。而且我无法得知默认样式有哪些

**Comment by peterroe** [comment]
或者说可以关掉脚手架提供的默认样式吗

**Comment by dewfall123** [comment]
css隔离这个问题应该晚些会解决下

**Comment by peterroe** [comment]
好的
