### ISSUE TITLE
dev时，<demo>的渲染时机过早

### ISSUE THREAD

**Issue by zhangshichun** [dewfall123/vitepress-for-component#49]
**Describe the bug**
dev 时，head中script还未完成加载，demo内组件的onMounted已经完成了执行

**To Reproduce**
第一步：在 `docs/public` 下创建 test.js
```javascript
window.TEST_FN = () => {
  console.log(123)
}
```
第二步：在 .md 文件中引入该script
```
---
head:
  - - script
    - src: '/test.js'
---
```
第三步：在demo或某个组件的onMounted里执行：
```javascript
  window.TEST_FN()
```
**Expected behavior**
期望：可以成功打印 123

**System Info**
- vitepress-for-component: 0.16.5
- vite: 2.6.14

**Comment by dewfall123** [comment]
可以这样引入script
```js
// .vitepress\config.js
...
head: [['script', { src: '/test.js' }]],
...
```
参考 https://github.com/vuejs/vitepress/issues/375

**Comment by zhangshichun** [comment]
> 可以这样引入script
> 
> ```js
> // .vitepress\config.js
> ...
> head: [['script', { src: '/test.js' }]],
> ...
> ```
> 
> 参考 [vuejs/vitepress#375](https://github.com/vuejs/vitepress/issues/375)

thank u! 有效
