### ISSUE TITLE
运行报错 

### ISSUE THREAD

**Issue by zhaoxm469** [dewfall123/vitepress-for-component#55]
您好，我尝试把这个项目拉取下来，想基于您这个自己二次开发。

但是当我拉取项目运行以后，浏览器提示报错，运行不起来。

![image](https://user-images.githubusercontent.com/26950016/150768353-aa68f242-2768-4652-ac76-41e3b3f732e0.png)

![image](https://user-images.githubusercontent.com/26950016/150769099-78921aa7-c307-452d-a358-19c7f7aa09f5.png)

电脑系统版本：macOs Big sur 11.6.2
npm版本：8.3.0
node版本：16.6.1
vitepress-for-component版本：0.16.9 ，分支：master

命令：
1. npm install 
2. npm run dev 
3. npm run docs

**Comment by dewfall123** [comment]
错误提示是403权限问题，看下`vitepress-for-components/dist/client/app/index.js` 文件夹的权限相关设置呢

我手里没有mac系统，复现不了

**Comment by zhaoxm469** [comment]
> 错误提示是403权限问题，看下`vitepress-for-components/dist/client/app/index.js` 文件夹的权限相关设置呢
> 
> 我手里没有mac系统，复现不了

非常感谢您的回复！
根据您的提示，我找到了问题原因，并成功解决了。

![image](https://user-images.githubusercontent.com/26950016/151175565-1856e303-59bb-4fd9-8e83-f7cf752c9482.png)
