### ISSUE TITLE
关于部署配置

### ISSUE THREAD

**Issue by aslkami** [dewfall123/vitepress-for-component#61]
我通过 脚手架  创建一个项目 vue-docs，用的这个 `vue-multiple-components`  模板, 打包部署在 netilfy 上。指定文档目录在 docs/dist，打开html 引入路径的 路径 通通都有 vue-docs/ , 导致 404

我尝试修改 base， title 这些，然后 执行 npm run docs-build， 依然没有修改成功

请问我应该怎么做？

**Comment by dewfall123** [comment]
你描述的应该就是base设置的问题。

改这个配置文件`docs\.vitepress\config.js`的base字段。

**Comment by aslkami** [comment]
> 你描述的应该就是base设置的问题。
> 
> 改这个配置文件`docs\.vitepress\config.js`的base字段。

为什么不是改 vite.config.js 呢， 我是在这里面改的

**Comment by dewfall123** [comment]
`vite.config.js`是打包src源码用到的配置，不是打包文档用到的

**Comment by dewfall123** [comment]
> 可是这个部署是提交代码之后，自动执行 npm run docs-build 打包的，根据你的意思 是得打包完成后再更改 `docs\.vitepress\config.js` ，貌似有点悖论 = =

 `npm run build`  对应`vite.config.js`配置，是打包src源码用到的配置。打包产物是dist/**，一般用于发布到npm。

 `npm run docs-build` 对应`docs\.vitepress\config.js`配置，是打包文档的。打包产物是docs/dist/**，即你部署文档站点用到的静态文件。

> 是得打包完成后再更改 docs\.vitepress\config.js

两个打包命令没有关系，不会互相影响。

**Comment by aslkami** [comment]
> > 可是这个部署是提交代码之后，自动执行 npm run docs-build 打包的，根据你的意思 是得打包完成后再更改 `docs\.vitepress\config.js` ，貌似有点悖论 = =
> 
> `npm run build` 对应`vite.config.js`配置，是打包src源码用到的配置。打包产物是dist/**，一般用于发布到npm。
> 
> `npm run docs-build` 对应`docs\.vitepress\config.js`配置，是打包文档的。打包产物是docs/dist/**，即你部署文档站点用到的静态文件。
> 
> > 是得打包完成后再更改 docs.vitepress\config.js
> 
> 两个打包命令没有关系，不会互相影响。

要不大佬瞅瞅，`https://aslkami-vue.netlify.app/` ，我是直接下载模板，然后部署的， 产物指向 确实是  `docs/dist/**` , 但是路径不对，默认给我添加了 vue-docs 的前缀， 我该怎么调整？

**Comment by dewfall123** [comment]
> 你描述的应该就是base设置的问题。
> 
> 改这个配置文件`docs\.vitepress\config.js`的base字段。

如果是你的这个项目的话，改下面这个文件第一行，把vue-docs去掉就行。
https://github.com/aslkami/vitepress/blob/main/docs/.vitepress/config.js

```js
// const base = process.env.NODE_ENV === 'production' ? '/vue-docs' : '';
const base = process.env.NODE_ENV === 'production' ? '' : '';
```

**Comment by aslkami** [comment]
> > 你描述的应该就是base设置的问题。
> > 改这个配置文件`docs\.vitepress\config.js`的base字段。
> 
> 如果是你的这个项目的话，改下面这个文件第一行，把vue-docs去掉就行。 https://github.com/aslkami/vitepress/blob/main/docs/.vitepress/config.js
> 
> ```js
> // const base = process.env.NODE_ENV === 'production' ? '/vue-docs' : '';
> const base = process.env.NODE_ENV === 'production' ? '' : '';
> ```

哦哦 可以了谢谢， 我以为这个 `.vitepress/config.js` 也是每次打包重新生成的
