### ISSUE TITLE
在workspaces下应该如何组织目录结构

### ISSUE THREAD

**Issue by lhlyu** [dewfall123/vitepress-for-component#7]
RT

**Comment by dewfall123** [comment]
没有限制目录结构。

**Comment by dewfall123** [comment]
可以参考下这个组件的结构 [仓库](https://github.com/dewfall123/ahooks-vue)。

**Comment by lhlyu** [comment]
> 可以参考下这个组件的结构 [仓库](https://github.com/dewfall123/ahooks-vue)。

。。这个看过了，就是想找个workspaces下的参考，没找到，还一堆报错

**Comment by dewfall123** [comment]
目录可以参考这个？ [dumi-目录](https://d.umijs.org/zh-CN/guide/basic)

报错是指？能否贴出来看下？

另外运行这个命令`yarn create vlib` 会生成一个示例项目，不知道是不是你想要的。

**Comment by lhlyu** [comment]
> 目录可以参考这个？ [dumi-目录](https://d.umijs.org/zh-CN/guide/basic)
> 
> 报错是指？能否贴出来看下？
> 
> 另外运行这个命令`yarn create vlib` 会生成一个示例项目，不知道是不是你想要的。

nice！
我尝试一下

**Comment by lhlyu** [comment]
可以了，还需要整理一下
[demo](https://github.com/lhlyu/caviar)
